In [2]:
import tensorflow as tf 
import tensorflow_datasets as tfds # to load training data


ModuleNotFoundError: No module named 'tensorflow_datasets'

In [3]:
!pip install tensorflow_datasets

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 7.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.3/164.3 kB 3.7 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.0/29.0 MB 9.0 MB/s eta 0:00:0000:01m00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.6/112.6 kB 272.8 kB/s eta 0:00:00 0:00:01
  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21484 sha256=afb46f1e3058f18a43c243fab547c03f7ed2294a6281eb88400163dc90ca7d94
  Stored in directory: /Users/aashish/Library/Caches/pip/wheels/90/74/b1/9b54c896b8d9409e9268329d4d45ede8a8040abe91c8879932
Successfully built promise


In [7]:
import tensorflow_datasets as tfds
DATA_DIR="./tensorflow-datasets"


In [146]:

tf.random.set_seed(1024)



#hyperparameter 1 batch_size = 8, batch_size = 32
#hyperparameter 2 optimizer=adam or sgd with default learning rate
early_stopping_callback = tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)
csv_logger = tf.keras.callbacks.CSVLogger(filename="experiment_log.csv")
model.compile(optimizer=tf.keras.optimizers.Adam(),loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])


model.summary()


Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape              ┃    Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ flatten_10 (Flatten)            │ (None, 784)               │          0 │
├─────────────────────────────────┼───────────────────────────┼────────────┤
│ dense_33 (Dense)                │ (None, 100)               │     78,500 │
├─────────────────────────────────┼───────────────────────────┼────────────┤
│ dense_34 (Dense)                │ (None, 100)               │     10,100 │
├─────────────────────────────────┼───────────────────────────┼────────────┤
│ dense_35 (Dense)                │ (None, 10)                │      1,010 │
└─────────────────────────────────┴───────────────────────────┴────────────┘

 Total params: 89,610 (350.04 KB)

 Trainable params: 89,610 (350.04 KB)

 Non-trainable params: 0 (0.00 B)

In [121]:
batch_size = 32

train_ds= tfds.load('fashion_mnist', split="train[:80%]",data_dir=DATA_DIR, shuffle_files=False).map(lambda x: (tf.cast(x['image'],tf.float32)/255.0, x['label'])).batch(batch_size)
val_ds= tfds.load('fashion_mnist', split="train[-20%:]",data_dir=DATA_DIR, shuffle_files=False).map(lambda x: (tf.cast(x['image'],tf.float32)/255.0, x['label'])).batch(batch_size)

# val_images,val_labels = tfds.load('fashion_mnist',split="train[-20%:]",shuffle_files=False,as_supervised=True).batch(batch_size)






In [122]:
model.fit(train_ds,validation_data=val_ds,epochs=100,callbacks=[early_stopping_callback,csv_logger])

Epoch 1/100


ValueError: FBetaScore expects 2D inputs with shape (batch_size, output_dim). Received input shapes: y_pred.shape=(None, 10) and y_true.shape=(None,).

In [155]:
import utils 

import numpy as np 
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix


def evaluate(model):
    test_ds = utils.get_test_set()
    predictions = model.predict(test_ds).argmax(axis=-1)
    gt = np.concatenate([y for _, y in test_ds], axis=0)
    acc_score = accuracy_score(gt,predictions)
    f1 = f1_score(gt,predictions,average="macro")
    cf = confusion_matrix(gt,predictions)
    return acc_score,f1,cf






313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


2024-09-29 22:02:39.015362: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


(0.8633,
 0.8604127472460448,
 array([[866,   1,  17,  18,   2,   1,  86,   0,   9,   0],
        [  4, 963,   2,  22,   5,   1,   2,   0,   1,   0],
        [ 19,   0, 843,  11,  85,   0,  40,   0,   2,   0],
        [ 48,   4,  10, 875,  42,   1,  19,   0,   1,   0],
        [  3,   0, 164,  13, 796,   0,  24,   0,   0,   0],
        [  0,   0,   0,   1,   0, 961,   0,  18,   0,  20],
        [192,   0, 169,  23, 127,   0, 480,   0,   9,   0],
        [  0,   0,   0,   0,   0,  35,   0, 948,   1,  16],
        [  6,   0,   4,   5,   5,   4,   7,   5, 964,   0],
        [  0,   0,   0,   0,   0,   8,   1,  54,   0, 937]]))

In [156]:
results = evaluate(model)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


2024-09-29 22:04:27.959710: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [168]:
import pickle 

pickle.dump(results,open("results","wb"))

In [170]:
results_1 = pickle.load(open("results","rb"))

(0.8633,
 0.8604127472460448,
 array([[866,   1,  17,  18,   2,   1,  86,   0,   9,   0],
        [  4, 963,   2,  22,   5,   1,   2,   0,   1,   0],
        [ 19,   0, 843,  11,  85,   0,  40,   0,   2,   0],
        [ 48,   4,  10, 875,  42,   1,  19,   0,   1,   0],
        [  3,   0, 164,  13, 796,   0,  24,   0,   0,   0],
        [  0,   0,   0,   1,   0, 961,   0,  18,   0,  20],
        [192,   0, 169,  23, 127,   0, 480,   0,   9,   0],
        [  0,   0,   0,   0,   0,  35,   0, 948,   1,  16],
        [  6,   0,   4,   5,   5,   4,   7,   5, 964,   0],
        [  0,   0,   0,   0,   0,   8,   1,  54,   0, 937]]))

In [119]:
pred

array([4, 4, 5, ..., 3, 6, 1])